import "./globals.css"
import 'remixicon/fonts/remixicon.css'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./Providers";
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Project",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html suppressHydrationWarning lang="en">
            <body>
                <Providers >
                    {children}
                </Providers>
            </body>
        </html>

    );
}